<x-app-layout>
    <main id="content" data-swiftype-index="true" tabindex="-1">
        <section id="1vBIMoxoTYg728FqlyyuOB" class="p23hero module module--noPadding backgroundCoconut"
            data-module-id="p23Hero" data-entry-id="1vBIMoxoTYg728FqlyyuOB" data-behavior="p23Hero ">
            <div class="p23hero__content flex flex--columns-2 mainContent__media_fullbleed">
                <div class="p23hero__mediaContainer__media_fullbleed">
                    <figure class="image__media_fullbleed">
                        <picture>
                            <source sizes="(min-width: 1600px) 1600px, 100vw"
                                srcset="{{ asset('assets/images/Owl Arm.webp') }}" type="image/avif" />
                            <source sizes="(min-width: 1600px) 1600px, 100vw"
                                srcset="{{ asset('assets/images/Owl Arm.webp') }}" type="image/webp" />
                            <img src="{{ asset('assets/images/Owl Arm.webp') }}" class="mediaImage__image"
                                sizes="(min-width: 1600px) 1600px, 100vw" width="1500" height="1164" />
                        </picture>
                    </figure>
                    <div style="font-size: 10px; font-weight: bold; padding: 2px">
                        Image Generated by AI
                    </div>
                </div>

                <div class="p23hero__copyContainer">
                    <div class="p23hero__copyHolder mainContainer__media_fullbleed">
                        <h1 class="h1" style="color: #056146 !important;">
                            Reimagine processes and transform experiences with connectOWL
                        </h1>
                        <div class="p23hero__copy copy-large margin--top-3">
                            <p>
                                Solution based on client need that easy to use and sure, affordable. With onboarding
                                support
                            </p>
                        </div>
                        <div class="flex flex--middle margin--top-5">
                            <div class="margin--right-3">
                                <a class="ctaPrimary" href="https://wa.me/6282286947001"
                                    aria-label="Direct to WhatsApp">
                                    Direct to WhatsApp
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="2beU2PaXDbH2DuQVtbVS6" class="p23HorizontalGrid module backgroundApricot"
            data-module-id="p23HorizontalGrid" data-entry-id="2beU2PaXDbH2DuQVtbVS6" data-behavior="p23HorizontalGrid">
            <div class="module--content">
                <div class="p23hg__section">
                    <ul data-equalizer="" class="p23HorizontalGrid__grid grid--columns-2">
                        <li class="p23HorizontalGrid__grid__gridItem" data-component-id="p23HorizontalGridUnlinkedItem"
                            data-entry-id="59sZmWhYG4cRvxxbbVoncG">
                            <div data-equalize-height="p23horizontalGrid_6dDTl9GxY6QIYcpNhnaeFQ" style="height: 96px">
                                <h2 class="p23hg__title copy-large" style="color: #F2C9E8 !important">
                                    Automation save 4 Hours a day
                                </h2>

                                <div class="copy-prose copy-small margin--top-2">
                                    <p style="color: #F2C9E8 !important">connectOWL helps improve business workflow</p>
                                </div>
                            </div>
                        </li>
                        <li class="p23HorizontalGrid__grid__gridItem" data-component-id="p23HorizontalGridUnlinkedItem"
                            data-entry-id="1IJHS7xtkMIf9GRXcOnmW7">
                            <div data-equalize-height="p23horizontalGrid_6dDTl9GxY6QIYcpNhnaeFQ" style="height: 96px">
                                <h2 class="p23hg__title copy-large" style="color: #F2C9E8 !important">Give more
                                    eXperience to Customers </h2>

                                <div class="copy-prose copy-small margin--top-2">
                                    <p style="color: #F2C9E8 !important">
                                        in
                                        <a style="color: #F2C9E8 !important;"
                                            href="https://portal.connectowl.io">connectOWL</a>
                                        giving best eXperience between users and customers
                                    </p>
                                </div>
                            </div>
                        </li>
                        <li class="p23HorizontalGrid__grid__gridItem" data-component-id="p23HorizontalGridUnlinkedItem"
                            data-entry-id="3FtjFUFzoiahnc8ukt9If8">
                            <div data-equalize-height="p23horizontalGrid_6dDTl9GxY6QIYcpNhnaeFQ" style="height: 96px">
                                <h2 class="p23hg__title copy-large" style="color: #F2C9E8 !important">
                                    98% Customers happy with fast respon time
                                </h2>

                                <div class="copy-prose copy-small margin--top-2">
                                    <p style="color: #F2C9E8 !important">
                                        yes, who’s gonna wait till tomorrow
                                    </p>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </section>
        <section class="p23FlexibleHighlight module backgroundSquash" id="65LsnjFlkgyI5nclHrc1wY"
            data-behavior="p23FlexibleHighlight" data-module-id="p23FlexibleHighlight"
            data-entry-id="65LsnjFlkgyI5nclHrc1wY">
            <div class="module--content align--center">
                <div class="column column1">
                    <figure class="image animate--show" data-animate="fade-up-in">
                        <picture>
                            <source sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                srcset="
                    {{ asset('assets/images/Whimsical Av.webp') }}?w=640&amp;fm=avif&amp;q=60   640w,
                    {{ asset('assets/images/Whimsical Av.webp') }}?w=842&amp;fm=avif&amp;q=60   842w,
                    {{ asset('assets/images/Whimsical Av.webp') }}?w=1280&amp;fm=avif&amp;q=60 1280w,
                    {{ asset('assets/images/Whimsical Av.webp') }}?w=1684&amp;fm=avif&amp;q=60 1684w
                  "
                                type="image/avif" />
                            <source sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                srcset="
                    {{ asset('assets/images/Whimsical Av.webp') }}?w=640&amp;fm=webp&amp;q=70   640w,
                    {{ asset('assets/images/Whimsical Av.webp') }}?w=842&amp;fm=webp&amp;q=70   842w,
                    {{ asset('assets/images/Whimsical Av.webp') }}?w=1280&amp;fm=webp&amp;q=70 1280w,
                    {{ asset('assets/images/Whimsical Av.webp') }}?w=1684&amp;fm=webp&amp;q=70 1684w
                  "
                                type="image/webp" />
                            <img src="{{ asset('assets/images/Whimsical Av.webp') }}"
                                srcset="
                    {{ asset('assets/images/Whimsical Av.webp') }}?w=640&amp;q=70   640w,
                    {{ asset('assets/images/Whimsical Av.webp') }}?w=842&amp;q=70   842w,
                    {{ asset('assets/images/Whimsical Av.webp') }}?w=1280&amp;q=70 1280w,
                    {{ asset('assets/images/Whimsical Av.webp') }}?w=1684&amp;q=70 1684w
                  "
                                sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                loading="lazy"
                                alt="An Intuit Assist prompt bar, reading “Generating… Applying your brand styles,” above a user interface with text that reads “(Beta) Promote a product or service: Let your customers know what’s new in your shop. We’ll populate your product information, brand styles, and content—all you have to do is review and send.” A button below the text reads “Generate draft.”"
                                width="1270" height="880" />
                        </picture>
                    </figure>
                    <div style="font-size: 10px; font-weight: bold; padding: 2px">
                        Image Generated by AI
                    </div>
                </div>
                <div class="column column2">
                    <h2 class="h2" style="color: #FF6D27 !important">
                        Don’t worry, connectOWL will connect you with everybody
                    </h2>
                    <p>
                        With a dedicated team of tech enthusiasts, we have crafted a Managed Service product called
                        connectOWL that caters to the diverse needs of a broad market
                    </p>
                    <p></p>
                    <div class="cta__holder cta__p23_arrow_link_small">
                        <a class="ctaArrow cta--small" href="portal.connectowl.io"
                            aria-label="Learn more for Manage Services">
                            Learn more for Manage Services
                        </a>
                    </div>
                </div>
            </div>
        </section>
        <section id="69Z6kTVJSEZ2apNxZsR3Xr" class="p23HorizontalGrid module backgroundPeppercorn"
            data-module-id="p23HorizontalGrid" data-entry-id="69Z6kTVJSEZ2apNxZsR3Xr"
            data-behavior="p23HorizontalGrid">
            <div class="module--content">
                <h2 class="h2 margin--bottom-5">
                    Explore main services of connectOWL
                </h2>

                <div class="p23hg__section">
                    <ul data-equalizer="" class="p23HorizontalGrid__grid grid--columns-new-2">
                        <li class="p23HorizontalGrid__grid__gridItem" data-component-id="p23HorizontalGridCompactItem"
                            data-entry-id="1SBvGxn4y6wIdkG5MT4H2q">
                            <div data-equalize-height="p23horizontalGrid_2vndgjbN7OyleuLKK1G31k"
                                style="height: 176px">
                                <a class="p23hg__itemCta" href="https://www.optiflow.connectowl.io">
                                    <figure class="p23hg__itemIcon">
                                        <picture>
                                            <source sizes="40px"
                                                srcset="
                            {{ asset('assets/icons/Marketing.png') }}?w=40&amp;fm=avif&amp;q=60
                          "
                                                type="image/avif" />
                                            <source sizes="40px"
                                                srcset="
                            {{ asset('assets/icons/Marketing.png') }}?w=40&amp;fm=webp&amp;q=70
                          "
                                                type="image/webp" />
                                            <img src="{{ asset('assets/icons/Marketing.png') }}" sizes="40px"
                                                loading="lazy" alt="" width="60" height="60" />
                                        </picture>
                                    </figure>
                                    <h3 class="h3 copy-medium copy--bold flex flex--nowrap p23hg__title margin--top-3">
                                        Automation Management System - OptiFlow
                                        <svg width="19" height="18" viewBox="0 0 19 18" fill="none"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path
                                                d="M14.9 10.2H1V8.2H14.9L9.3 2.4L10.8 1L18.4 9.2L10.8 17.4L9.3 16L14.9 10.2Z"
                                                fill="currentColor"></path>
                                        </svg>
                                    </h3>

                                    <p class="margin--top-2 copy-small">
                                        Automation systems to improve operational efficiency and automate business
                                        processes to increase productivity
                                    </p>
                                </a>
                            </div>
                        </li>
                        <li class="p23HorizontalGrid__grid__gridItem" data-component-id="p23HorizontalGridCompactItem"
                            data-entry-id="1UtrrsKF3HSvYz7fE4b3EK">
                            <div data-equalize-height="p23horizontalGrid_2vndgjbN7OyleuLKK1G31k"
                                style="height: 176px">
                                <a class="p23hg__itemCta" href="https://www.classsphere.connectowl.io">
                                    <figure class="p23hg__itemIcon">
                                        <picture>
                                            <source sizes="40px"
                                                srcset="
                            {{ asset('assets/icons/Online Education.png') }}?w=40&amp;fm=avif&amp;q=60
                          "
                                                type="image/avif" />
                                            <source sizes="40px"
                                                srcset="
                            {{ asset('assets/icons/Online Education.png') }}?w=40&amp;fm=webp&amp;q=70
                          "
                                                type="image/webp" />
                                            <img src="{{ asset('assets/icons/Online Education.png') }}"
                                                sizes="40px" loading="lazy" alt="" width="61"
                                                height="60" />
                                        </picture>
                                    </figure>
                                    <h3 class="h3 copy-medium copy--bold flex flex--nowrap p23hg__title margin--top-3">
                                        Learning Management System(LMS) - ClassSphere
                                        <svg width="19" height="18" viewBox="0 0 19 18" fill="none"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path
                                                d="M14.9 10.2H1V8.2H14.9L9.3 2.4L10.8 1L18.4 9.2L10.8 17.4L9.3 16L14.9 10.2Z"
                                                fill="currentColor"></path>
                                        </svg>
                                    </h3>

                                    <p class="margin--top-2 copy-small">
                                        An integrated software platform for managing online training and learning
                                        programs, including course management, materials, and evaluation.
                                    </p>
                                </a>
                            </div>
                        </li>
                        <li class="p23HorizontalGrid__grid__gridItem" data-component-id="p23HorizontalGridCompactItem"
                            data-entry-id="104yX7ItKtpxI4QbS5iwKN">
                            <div data-equalize-height="p23horizontalGrid_2vndgjbN7OyleuLKK1G31k"
                                style="height: 176px">
                                <a class="p23hg__itemCta" href="#">
                                    <figure class="p23hg__itemIcon">
                                        <picture>
                                            <source sizes="40px"
                                                srcset="
                            {{ asset('assets/icons/AI 2.png') }}?w=40&amp;fm=avif&amp;q=60
                          "
                                                type="image/avif" />
                                            <source sizes="40px"
                                                srcset="
                            {{ asset('assets/icons/AI 2.png') }}?w=40&amp;fm=webp&amp;q=70
                          "
                                                type="image/webp" />
                                            <img src="{{ asset('assets/icons/AI 2.png') }}" sizes="40px"
                                                loading="lazy" alt="" width="61" height="60" />
                                        </picture>
                                    </figure>
                                    <h3 class="h3 copy-medium copy--bold flex flex--nowrap p23hg__title margin--top-3">
                                        AI-Driven
                                        <svg width="19" height="18" viewBox="0 0 19 18" fill="none"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path
                                                d="M14.9 10.2H1V8.2H14.9L9.3 2.4L10.8 1L18.4 9.2L10.8 17.4L9.3 16L14.9 10.2Z"
                                                fill="currentColor"></path>
                                        </svg>
                                    </h3>

                                    <p class="margin--top-2 copy-small">
                                        With AI help better result, experience and the way you use the application
                                    </p>
                                </a>
                            </div>
                        </li>
                        <li class="p23HorizontalGrid__grid__gridItem" data-component-id="p23HorizontalGridCompactItem"
                            data-entry-id="zOMggB7XB0FqM8d6rFtJr">
                            <div data-equalize-height="p23horizontalGrid_2vndgjbN7OyleuLKK1G31k"
                                style="height: 176px">
                                <a class="p23hg__itemCta" href="https://www.exmanage.connectowl.io">
                                    <figure class="p23hg__itemIcon">
                                        <picture>
                                            <source sizes="40px"
                                                srcset="
                            {{ asset('assets/icons/Practice (1).png') }}?w=40&amp;fm=avif&amp;q=60
                          "
                                                type="image/avif" />
                                            <source sizes="40px"
                                                srcset="
                            {{ asset('assets/icons/Practice (1).png') }}?w=40&amp;fm=webp&amp;q=70
                          "
                                                type="image/webp" />
                                            <img src="{{ asset('assets/icons/Practice (1).png') }}" sizes="40px"
                                                loading="lazy" alt="" width="60" height="60" />
                                        </picture>
                                    </figure>
                                    <h3 class="h3 copy-medium copy--bold flex flex--nowrap p23hg__title margin--top-3">
                                        Experience Management - eXmanage
                                        <svg width="19" height="18" viewBox="0 0 19 18" fill="none"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path
                                                d="M14.9 10.2H1V8.2H14.9L9.3 2.4L10.8 1L18.4 9.2L10.8 17.4L9.3 16L14.9 10.2Z"
                                                fill="currentColor"></path>
                                        </svg>
                                    </h3>

                                    <p class="margin--top-2 copy-small">
                                        Solutions to integrate and manage multiple communication and sales channels,
                                        enabling a seamless consumer experience across multiple platforms.
                                    </p>
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </section>
        <section id="4CZBzRmthW5ZtkTejeBQuD" class="p23HorizontalGrid module backgroundCoconut"
            data-module-id="p23HorizontalGrid" data-entry-id="4CZBzRmthW5ZtkTejeBQuD"
            data-behavior="p23HorizontalGrid">
            <div class="module--content">
                <div class="margin--bottom-6">
                    <h2 class="h2">connect All or connectOWL?</h2>
                    <p>Connect Orchestrated, Well-tailored Lifecycle</p>
                </div>
                <div class="p23hg__section">
                    <ul data-equalizer="" class="p23HorizontalGrid__grid grid--columns-3">
                        <li class="p23HorizontalGrid__grid__gridItem" data-component-id="p23HorizontalGridItem"
                            data-entry-id="6Q2eyBWII0coXceXFA0Q6">
                            <div data-equalize-height="p23horizontalGrid_1YUz8AsxacvX6InSBAjGQ6"
                                style="height: 383px">
                                <a class="p23hg__itemCta"
                                    href="https://mailchimp.com/resources/mailchimp-vs-klaviyo/">
                                    <figure>
                                        <picture>
                                            <source sizes="820px"
                                                srcset="
                            {{ asset('assets/images/DALL·.webp') }}?w=820&amp;fm=avif&amp;q=60   820w,
                            {{ asset('assets/images/DALL·.webp') }}?w=1640&amp;fm=avif&amp;q=60 1640w
                          "
                                                type="image/avif" />
                                            <source sizes="820px"
                                                srcset="
                            {{ asset('assets/images/DALL·.webp') }}?w=820&amp;fm=webp&amp;q=70   820w,
                            {{ asset('assets/images/DALL·.webp') }}?w=1640&amp;fm=webp&amp;q=70 1640w
                          "
                                                type="image/webp" />
                                            <img src="{{ asset('assets/images/DALL·.webp') }}"
                                                srcset="
                            {{ asset('assets/images/DALL·.webp') }}?w=820&amp;q=70   820w,
                            {{ asset('assets/images/DALL·.webp') }}?w=1640&amp;q=70 1640w
                          "
                                                sizes="820px" loading="lazy"
                                                alt="A product email, sent from Mailchimp. In bubbles around it are the logos of various integrations that work with Mailchimp."
                                                width="1240" height="696" />
                                        </picture>
                                    </figure>
                                    <h3 class="p23hg__title copy-large margin--top-4">
                                        Orchestrated
                                    </h3>

                                    <p class="margin--top-2 copy-small">
                                        Managed services by ConnectOWL are expertly organized, ensuring a seamless and
                                        integrated approach to IT management.
                                    </p>
                                </a>
                            </div>

                            <a class="ctaArrow cta--small" href="#" aria-label="Learn more">
                                Learn more
                            </a>
                        </li>
                        <li class="p23HorizontalGrid__grid__gridItem" data-component-id="p23HorizontalGridItem"
                            data-entry-id="4G6jiUHzTCtd0xLiGsbIOd">
                            <div data-equalize-height="p23horizontalGrid_1YUz8AsxacvX6InSBAjGQ6"
                                style="height: 383px">
                                <a class="p23hg__itemCta" href="#">
                                    <figure>
                                        <picture>
                                            <source sizes="820px"
                                                srcset="
                            {{ asset('assets/images/DALL·E Landscape Oil Pastel.webp') }}?w=820&amp;fm=avif&amp;q=60   820w,
                            {{ asset('assets/images/DALL·E Landscape Oil Pastel.webp') }}?w=1640&amp;fm=avif&amp;q=60 1640w
                          "
                                                type="image/avif" />
                                            <source sizes="820px"
                                                srcset="
                            {{ asset('assets/images/DALL·E Landscape Oil Pastel.webp') }}?w=820&amp;fm=webp&amp;q=70   820w,
                            {{ asset('assets/images/DALL·E Landscape Oil Pastel.webp') }}?w=1640&amp;fm=webp&amp;q=70 1640w
                          "
                                                type="image/webp" />
                                            <img src="{{ asset('assets/images/DALL·E Landscape Oil Pastel.webp') }}"
                                                srcset="
                            {{ asset('assets/images/DALL·E Landscape Oil Pastel.webp') }}?w=820&amp;q=70   820w,
                            {{ asset('assets/images/DALL·E Landscape Oil Pastel.webp') }}?w=1640&amp;q=70 1640w
                          "
                                                sizes="820px" loading="lazy"
                                                alt="A customer behavior trigger with 4 options. Four different customer profiles to their right."
                                                width="1240" height="696" />
                                        </picture>
                                    </figure>
                                    <h3 class="p23hg__title copy-large margin--top-4">
                                        Well-tailored
                                    </h3>

                                    <p class="margin--top-2 copy-small">
                                        ConnectOWL provides welldesigned solutions, customizing managed services to meet
                                        the specific needs of each client
                                    </p>
                                </a>
                            </div>

                            <a class="ctaArrow cta--small"
                                href="https://mailchimp.com/resources/mailchimp-vs-hubspot/" aria-label="Learn more">
                                Learn more
                            </a>
                        </li>
                        <li class="p23HorizontalGrid__grid__gridItem" data-component-id="p23HorizontalGridItem"
                            data-entry-id="30vKOmUeCKQpjsUA0vDlUo">
                            <div data-equalize-height="p23horizontalGrid_1YUz8AsxacvX6InSBAjGQ6"
                                style="height: 383px">
                                <a class="p23hg__itemCta"
                                    href="https://mailchimp.com/resources/mailchimp-vs-activecampaign/">
                                    <figure>
                                        <picture>
                                            <source sizes="820px"
                                                srcset="
                            {{ asset('assets/images/DALL·E Landscape Lifecycle.webp') }}?w=820&amp;fm=avif&amp;q=60   820w,
                            {{ asset('assets/images/DALL·E Landscape Lifecycle.webp') }}?w=1640&amp;fm=avif&amp;q=60 1640w
                          "
                                                type="image/avif" />
                                            <source sizes="820px"
                                                srcset="
                            {{ asset('assets/images/DALL·E Landscape Lifecycle.webp') }}?w=820&amp;fm=webp&amp;q=70   820w,
                            {{ asset('assets/images/DALL·E Landscape Lifecycle.webp') }}?w=1640&amp;fm=webp&amp;q=70 1640w
                          "
                                                type="image/webp" />
                                            <img src="{{ asset('assets/images/DALL·E Landscape Lifecycle.webp') }}"
                                                srcset="
                            {{ asset('assets/images/DALL·E Landscape Lifecycle.webp') }}?w=820&amp;q=70   820w,
                            {{ asset('assets/images/DALL·E Landscape Lifecycle.webp') }}?w=1640&amp;q=70 1640w
                          "
                                                sizes="820px" loading="lazy"
                                                alt="Two SMS messages sent from Mailchimp. To their left is a journey flow determining whether to send a customer a reward SMS or a loyalty sign-up SMS.

"
                                                width="1240" height="696" />
                                        </picture>
                                    </figure>
                                    <h3 class="p23hg__title copy-large margin--top-4">
                                        Lifecycle
                                    </h3>

                                    <p class="margin--top-2 copy-small">
                                        ConnectOWL manages the entire IT lifecycle, offering comprehensive support from
                                        planning and implementation to ongoing optimization.
                                    </p>
                                </a>
                            </div>

                            <a class="ctaArrow cta--small"
                                href="https://mailchimp.com/resources/mailchimp-vs-activecampaign/"
                                aria-label="Learn more">
                                Learn more
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </section>
        <section class="p23FlexibleHighlight module backgroundSquash" id="16fO9QJysk5djMPxlwjm9A"
            data-behavior="p23FlexibleHighlight" data-module-id="p23FlexibleHighlight"
            data-entry-id="16fO9QJysk5djMPxlwjm9A">
            <div class="module--content align--center">
                <div class="column column1">
                    <h2 class="h2">
                        OptiFlow can automate your daily task
                    </h2>
                    <p>
                        Our automation management system is perfect fit for your daily task and save hours
                    </p>
                    <p></p>
                    <div class="cta__holder cta__p23_arrow_link_small">
                        <a class="ctaArrow cta--small" href="#" aria-label="Explore OptiFlow">
                            Explore OptiFlow
                        </a>
                    </div>
                </div>
                <div class="column column2">
                    <figure class=" image animate--show" data-animate="fade-up-in">
                        <picture>
                            <source sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                srcset="
                            {{ asset('assets/images/DALL·E Feb 27 Landscape Owls.webp') }}   640w,
                            {{ asset('assets/images/DALL·E Feb 27 Landscape Owls.webp') }}  842w,
                            {{ asset('assets/images/DALL·E Feb 27 Landscape Owls.webp') }} 1280w,
                            {{ asset('assets/images/DALL·E Feb 27 Landscape Owls.webp') }}  1684w
                        "
                                type="image/avif" />
                            <source sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                srcset="
                                    {{ asset('assets/images/DALL·E Feb 27 Landscape Owls.webp') }}  640w,
                                    {{ asset('assets/images/DALL·E Feb 27 Landscape Owls.webp') }}  842w,
                                    {{ asset('assets/images/DALL·E Feb 27 Landscape Owls.webp') }} 1280w,
                                    {{ asset('assets/images/DALL·E Feb 27 Landscape Owls.webp') }}  1684w
                                "
                                type="image/webp" />
                            <img src="{{ asset('assets/images/DALL·E Feb 27 Landscape Owls.webp') }}"
                                sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                loading="lazy" width="1905" height="1320" />
                        </picture>
                    </figure>
                    <div style="font-size: 10px; font-weight: bold; padding: 2px">
                        Image Generated by AI
                    </div>
                </div>
            </div>
        </section>
        <section class="p23FlexibleHighlight module backgroundApricot" id="3wY4ue4Ymhl7B8UjaUs2X5"
            data-behavior="p23FlexibleHighlight" data-module-id="p23FlexibleHighlight"
            data-entry-id="3wY4ue4Ymhl7B8UjaUs2X5">
            <div class="module--content align--center">
                <div class="column column1">
                    <figure class="image animate--show" data-animate="fade-up-in">
                        <picture>
                            <source sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                srcset="
                    {{ asset('assets/images/bear.webp') }}?w=640&amp;fm=avif&amp;q=60   640w,
                    {{ asset('assets/images/bear.webp') }}?w=842&amp;fm=avif&amp;q=60   842w,
                    {{ asset('assets/images/bear.webp') }}?w=1280&amp;fm=avif&amp;q=60 1280w,
                    {{ asset('assets/images/bear.webp') }}?w=1684&amp;fm=avif&amp;q=60 1684w
                  "
                                type="image/avif" />
                            <source sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                srcset="
                    {{ asset('assets/images/bear.webp') }}?w=640&amp;fm=webp&amp;q=70   640w,
                    {{ asset('assets/images/bear.webp') }}?w=842&amp;fm=webp&amp;q=70   842w,
                    {{ asset('assets/images/bear.webp') }}?w=1280&amp;fm=webp&amp;q=70 1280w,
                    {{ asset('assets/images/bear.webp') }}?w=1684&amp;fm=webp&amp;q=70 1684w
                  "
                                type="image/webp" />
                            <img src="{{ asset('assets/images/bear.webp') }}"
                                srcset="
                    {{ asset('assets/images/bear.webp') }}?w=640&amp;q=70   640w,
                    {{ asset('assets/images/bear.webp') }}?w=842&amp;q=70   842w,
                    {{ asset('assets/images/bear.webp') }}?w=1280&amp;q=70 1280w,
                    {{ asset('assets/images/bear.webp') }}?w=1684&amp;q=70 1684w
                  "
                                sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                loading="lazy"
                                alt="A user interface from within Mailchimp, containing a list of contacts. The heading of the list reads: “Your most loyal customers.”"
                                width="1905" height="1320" />
                        </picture>
                    </figure>
                    <div style="font-size: 10px; font-weight: bold; padding: 2px; color: white">
                        Image Generated by AI
                    </div>
                </div>
                <div class="column column2" style="color: #F2C9E8 !important">
                    <h2 class="h2" style="color: #F2C9E8 !important">
                        In ClassSphere even a bear is having fun
                    </h2>
                    <p>
                        Learning management system is adigital platform that organizes and delivers educational content,
                        tracks progress, and manages users, facilitating online learning and training.
                    </p>
                    <p></p>
                    <div class="cta__holder cta__primary">
                        <a class="ctaPrimary" href="https://mailchimp.com/sales/" aria-label="Talk to Sales">
                            Talk to Sales
                        </a>
                    </div>
                </div>
            </div>
        </section>

        <section class="p23FlexibleHighlight module backgroundSquash" id="16fO9QJysk5djMPxlwjm9A"
            data-behavior="p23FlexibleHighlight" data-module-id="p23FlexibleHighlight"
            data-entry-id="16fO9QJysk5djMPxlwjm9A">
            <div class="module--content align--center">
                <div class="column column1">
                    <h2 class="h2">
                        eXmanage makes joyfull experience Connect All(OWL) Customer
                    </h2>
                    <p>
                        With our experience management, you can manage most famous channel with one lovely platform
                        called eXmanage
                    </p>
                    <p></p>
                    <div class="cta__holder cta__p23_arrow_link_small">
                        <a class="ctaArrow cta--small" href="exmanage.connectowl.io" aria-label="Explore OptiFlow">
                            Explore eXmanage
                        </a>
                    </div>
                </div>
                <div class="column column2">
                    <figure class=" image animate--show" data-animate="fade-up-in">
                        <picture>
                            <source sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                srcset="
                            {{ asset('assets/images/Omnichannel Team Inbox.png') }}   640w,
                            {{ asset('assets/images/Omnichannel Team Inbox.png') }}  842w,
                            {{ asset('assets/images/Omnichannel Team Inbox.png') }} 1280w,
                            {{ asset('assets/images/Omnichannel Team Inbox.png') }}  1684w
                        "
                                type="image/avif" />
                            <source sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                srcset="
                                    {{ asset('assets/images/Omnichannel Team Inbox.png') }}  640w,
                                    {{ asset('assets/images/Omnichannel Team Inbox.png') }}  842w,
                                    {{ asset('assets/images/Omnichannel Team Inbox.png') }} 1280w,
                                    {{ asset('assets/images/Omnichannel Team Inbox.png') }}  1684w
                                "
                                type="image/webp" />
                            <img src="{{ asset('assets/images/Omnichannel Team Inbox.png') }}"
                                sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                loading="lazy" width="1905" height="1320" />
                        </picture>
                    </figure>
                    <div style="font-size: 10px; font-weight: bold; padding: 2px;">
                        Image Generated by AI
                    </div>
                </div>
            </div>
        </section>

        <div class="p23Headliner
                        module backgroundCoconut" id="6xPiXenYqwyz13cDFvCBuA"
            data-behavior="p23Headliner" data-module-id="p23Headliner" data-entry-id="6xPiXenYqwyz13cDFvCBuA"
            data-context-text="Start with confidence with our personalized onboarding—included with a Standard or Premium plan*">
            <div class="module--content module--content-8of12 align--center">
                <h2 class="h2">
                    Embark on a journey of growth and innovation; partner with us to transform your vision into reality!
                </h2>
                <div class="margin--top-3 copy-large">
                    <p>
                        Learning a new platform has never been so easy; our onboarding team provides illuminating
                        solutions to ensure your seamless transition.
                    </p>
                </div>
            </div>
        </div>
        <section class="p23FlexibleHighlight module backgroundCoconut" id="5e9M1MzIVbgXkssXMpFL8N"
            data-behavior="p23FlexibleHighlight" data-module-id="p23FlexibleHighlight"
            data-entry-id="5e9M1MzIVbgXkssXMpFL8N">
            <div class="module--content align--center">
                <div class="column column1">
                    <figure class="image animate--show" data-animate="fade-up-in">
                        <picture>
                            <source sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                srcset="
                    {{ asset('assets/images/DALL·E Casual Office.webp') }}?w=640&amp;fm=avif&amp;q=60   640w,
                    {{ asset('assets/images/DALL·E Casual Office.webp') }}?w=842&amp;fm=avif&amp;q=60   842w,
                    {{ asset('assets/images/DALL·E Casual Office.webp') }}?w=1280&amp;fm=avif&amp;q=60 1280w,
                    {{ asset('assets/images/DALL·E Casual Office.webp') }}?w=1684&amp;fm=avif&amp;q=60 1684w
                  "
                                type="image/avif" />
                            <source sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                srcset="
                    {{ asset('assets/images/DALL·E Casual Office.webp') }}?w=640&amp;fm=webp&amp;q=70   640w,
                    {{ asset('assets/images/DALL·E Casual Office.webp') }}?w=842&amp;fm=webp&amp;q=70   842w,
                    {{ asset('assets/images/DALL·E Casual Office.webp') }}?w=1280&amp;fm=webp&amp;q=70 1280w,
                    {{ asset('assets/images/DALL·E Casual Office.webp') }}?w=1684&amp;fm=webp&amp;q=70 1684w
                  "
                                type="image/webp" />
                            <img src="{{ asset('assets/images/DALL·E Casual Office.webp') }}"
                                srcset="
                    {{ asset('assets/images/DALL·E Casual Office.webp') }}?w=640&amp;q=70   640w,
                    {{ asset('assets/images/DALL·E Casual Office.webp') }}?w=842&amp;q=70   842w,
                    {{ asset('assets/images/DALL·E Casual Office.webp') }}?w=1280&amp;q=70 1280w,
                    {{ asset('assets/images/DALL·E Casual Office.webp') }}?w=1684&amp;q=70 1684w
                  "
                                sizes="(min-width: 88.888888888889em) 640px, (min-width: 62em) 45vw, 85vw"
                                loading="lazy"
                                alt="A birds-eye-view of an office, containing coworkers at their desks, working and chatting."
                                width="1905" height="1320" />
                        </picture>
                    </figure>
                    <div style="font-size: 10px; font-weight: bold; padding: 2px">
                        Image Generated by AI
                    </div>
                </div>
                <div class="column column2">
                    <h2 class="h2">
                        Empowering Your Success: Meet Our Dedicated Customer Success Manager
                    </h2>
                    <p>
                        Our Customer Success Manager is your personal guide, dedicated to ensuring your satisfaction and
                        success with our services. By understanding your needs and goals, they provide customized
                        support, facilitate smooth onboarding, and help you maximize the value you get from our
                        solutions
                    </p>
                    <p></p>
                    <div class="cta__holder cta__p23_arrow_link_small">
                        <a class="ctaArrow cta--small"
                            href="https://mailchimp.com/services/customer-success-management/                                        "
                            aria-label="Explore Customer Success">
                            Explore Customer Success
                        </a>
                    </div>
                </div>
            </div>
        </section>
        <section id="3Gf2bbfx8AFm4lrTPmDDN9" class="p23HorizontalGrid module backgroundCoconut"
            data-module-id="p23HorizontalGrid" data-entry-id="3Gf2bbfx8AFm4lrTPmDDN9"
            data-behavior="p23HorizontalGrid">
            <div class="module--content">
                <div class="p23hg__section">
                    <ul data-equalizer="" class="p23HorizontalGrid__grid grid--columns-3">
                        <li class="p23HorizontalGrid__grid__gridItem" data-component-id="p23HorizontalGridItem"
                            data-entry-id="1jN2Xsr32JEge8sNOSQGQW">
                            <div data-equalize-height="p23horizontalGrid_pkO5yc6Sa7XOivBXXy4tU" style="height: 384px">
                                <a class="p23hg__itemCta" href="https://mailchimp.com/services/onboarding/">
                                    <figure>
                                        <picture>
                                            <source sizes="820px"
                                                srcset="
                            {{ asset('assets/images/DALL·E imaginative art scene.webp') }}?w=820&amp;fm=avif&amp;q=60   820w,
                            {{ asset('assets/images/DALL·E imaginative art scene.webp') }}?w=1640&amp;fm=avif&amp;q=60 1640w
                          "
                                                type="image/avif" />
                                            <source sizes="820px"
                                                srcset="
                            {{ asset('assets/images/DALL·E imaginative art scene.webp') }}?w=820&amp;fm=webp&amp;q=70   820w,
                            {{ asset('assets/images/DALL·E imaginative art scene.webp') }}?w=1640&amp;fm=webp&amp;q=70 1640w
                          "
                                                type="image/webp" />
                                            <img src="{{ asset('assets/images/DALL·E imaginative art scene.webp') }}"
                                                srcset="
                            {{ asset('assets/images/DALL·E imaginative art scene.webp') }}?w=820&amp;q=70   820w,
                            {{ asset('assets/images/DALL·E imaginative art scene.webp') }}?w=1640&amp;q=70 1640w
                          "
                                                sizes="820px" loading="lazy"
                                                alt="A woman in an office, speaking on her cell phone while she works on her laptop. "
                                                width="800" height="449" />
                                        </picture>
                                    </figure>
                                    <h2 class="p23hg__title copy-large margin--top-4">
                                        Onboarding Services
                                    </h2>

                                    <p class="margin--top-2 copy-small">
                                        Our comprehensive onboarding services are designed to streamline your transition
                                        into the company, ensuring a smooth and welcoming start to your journey with us
                                    </p>
                                </a>
                            </div>
                        </li>
                        <li class="p23HorizontalGrid__grid__gridItem" data-component-id="p23HorizontalGridItem"
                            data-entry-id="7vUMRBETxOSZIFY0NKcEO9">
                            <div data-equalize-height="p23horizontalGrid_pkO5yc6Sa7XOivBXXy4tU" style="height: 384px">
                                <a class="p23hg__itemCta" href="https://mailchimp.com/help/">
                                    <figure>
                                        <picture>
                                            <source sizes="820px"
                                                srcset="
                            {{ asset('assets/images/DALL·E Feb 26.webp') }}?w=820&amp;fm=avif&amp;q=60   820w,
                            {{ asset('assets/images/DALL·E Feb 26.webp') }}?w=1640&amp;fm=avif&amp;q=60 1640w
                          "
                                                type="image/avif" />
                                            <source sizes="820px"
                                                srcset="
                            {{ asset('assets/images/DALL·E Feb 26.webp') }}?w=820&amp;fm=webp&amp;q=70   820w,
                            {{ asset('assets/images/DALL·E Feb 26.webp') }}?w=1640&amp;fm=webp&amp;q=70 1640w
                          "
                                                type="image/webp" />
                                            <img src="{{ asset('assets/images/DALL·E Feb 26.webp') }}"
                                                srcset="
                            {{ asset('assets/images/DALL·E Feb 26.webp') }}?w=820&amp;q=70   820w,
                            {{ asset('assets/images/DALL·E Feb 26.webp') }}?w=1640&amp;q=70 1640w
                          "
                                                sizes="820px" loading="lazy"
                                                alt="A coworker holds open her laptop and points to its screen. Another coworker, seated next to her, touches her arm and leans in."
                                                width="798" height="449" />
                                        </picture>
                                    </figure>
                                    <h2 class="p23hg__title copy-large margin--top-4">
                                        24/7 Chat &amp; Email Support
                                    </h2>

                                    <p class="margin--top-2 copy-small">
                                        Experience unparalleled convenience with our 24/7 email and chat support, ready
                                        to assist you around the clock with any inquiries or issues
                                    </p>
                                </a>
                            </div>
                        </li>
                        <li class="p23HorizontalGrid__grid__gridItem" data-component-id="p23HorizontalGridItem"
                            data-entry-id="4YQVMPQag9hn8EAHbK7Ekr">
                            <div data-equalize-height="p23horizontalGrid_pkO5yc6Sa7XOivBXXy4tU" style="height: 384px">
                                <a class="p23hg__itemCta" href="https://mailchimp.com/experts/">
                                    <figure>
                                        <picture>
                                            <source sizes="820px"
                                                srcset="
                            {{ asset('assets/images/DALL·E dynamic.webp') }}?w=820&amp;fm=avif&amp;q=60   820w,
                            {{ asset('assets/images/DALL·E dynamic.webp') }}?w=1640&amp;fm=avif&amp;q=60 1640w
                          "
                                                type="image/avif" />
                                            <source sizes="820px"
                                                srcset="
                            {{ asset('assets/images/DALL·E dynamic.webp') }}?w=820&amp;fm=webp&amp;q=70   820w,
                            {{ asset('assets/images/DALL·E dynamic.webp') }}?w=1640&amp;fm=webp&amp;q=70 1640w
                          "
                                                type="image/webp" />
                                            <img src="{{ asset('assets/images/DALL·E dynamic.webp') }}"
                                                srcset="
                            {{ asset('assets/images/DALL·E dynamic.webp') }}?w=820&amp;q=70   820w,
                            {{ asset('assets/images/DALL·E dynamic.webp') }}?w=1640&amp;q=70 1640w
                          "
                                                sizes="820px" loading="lazy"
                                                alt="Three coworkers sit across from each other. The one in the middle holds a laptop, and the one on the right holds a book and a pen."
                                                width="800" height="449" />
                                        </picture>
                                    </figure>
                                    <h2 class="p23hg__title copy-large margin--top-4">
                                        connectOWL Experts
                                    </h2>

                                    <p class="margin--top-2 copy-small">
                                        Unlock the full potential of your projects with ConnectOWL Experts, where
                                        seasoned professionals are at your service to provide tailored advice and
                                        solutions
                                    </p>
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </section>
        <div class="p23Headliner module backgroundPeppercorn" id="6EgDD87fKJhAefoJrW6lfh"
            data-behavior="p23Headliner" data-module-id="p23Headliner" data-entry-id="6EgDD87fKJhAefoJrW6lfh"
            data-context-text="Ready to make the switch?">
            <div class="module--content module--content-8of12 align--center">
                <h2 class="h2">Prepared to enhance your experience?</h2>
                <div class="margin--top-3 copy-large">
                    <p>Contact with our sales</p>
                </div>
                <div class="flex flex--middle margin--top-5 ctas__wrapper">
                    <div>
                        <a class="ctaPrimary" href="https://mailchimp.com/sales/" aria-label="Talk to Sales">
                            Direct to WhatsApp
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </main>
</x-app-layout>
